(()=>{"use strict";
const R="salitaQuestLocalProfilesV1",A="salitaQuestActiveProfileId",P="salitaQuestProgress",O="salitaQuestBaseProgressOwner",X="salitaQuestProgress.profile.",L=["salitaQuestStateV3","salitaQuestStateV2","salitaQuestState"];
const V=[
["tarsier","Philippine Tarsier","A tiny forest primate known for its enormous eyes and incredible jumping ability."],
["eagle","Philippine Eagle","A powerful forest eagle with a striking feathered crest and impressive wingspan."],
["tamaraw","Tamaraw","A rare wild buffalo found only on the Philippine island of Mindoro."],
["peacock","Palawan Peacock-Pheasant","A beautiful forest bird with shimmering blue-green feathers and a delicate crest."],
["orchid","Waling-Waling Orchid","A spectacular Philippine orchid admired for its large, colourful flowers."],
["jade","Jade Vine","A tropical climbing plant with unusual turquoise flowers shaped like curved claws."],
["rafflesia","Philippine Rafflesia","A remarkable rainforest flower known for its enormous, spotted red petals."],
["anahaw","Anahaw","A native fan palm whose broad green leaves are a familiar Philippine symbol."]].map(([id,title,description])=>({id,title,description,src:`avatars/${id}.png`}));
const q=s=>document.querySelector(s),gate=q("#profileGate"),panel=q("#profilePanel"),stage=q("#appStage"),frame=q("#salitaApp"),toast=q("#profileToast");let active=null,timer=null,last=null;
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const av=id=>V.find(x=>x.id===id)||V[0];
function read(){try{let r=JSON.parse(localStorage.getItem(R)||"null");return r&&Array.isArray(r.profiles)?r:{schemaVersion:1,profiles:[]}}catch{return{schemaVersion:1,profiles:[]}}}
function write(r){r.schemaVersion=1;r.updatedAt=new Date().toISOString();localStorage.setItem(R,JSON.stringify(r))}
const key=id=>X+id;
function id(){return crypto.randomUUID?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function salt(){return[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hash(pin,s){let d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${s}:${pin}`));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function note(m){toast.textContent=m;toast.hidden=false;clearTimeout(note.t);note.t=setTimeout(()=>toast.hidden=true,3000)}
function legacy(){let v=localStorage.getItem(P);if(v)return v;for(let k of L){v=localStorage.getItem(k);if(v)return v}return null}
function recover(){let o=localStorage.getItem(O),v=localStorage.getItem(P);if(o&&v&&read().profiles.some(p=>p.id===o))localStorage.setItem(key(o),v)}
function clear(){localStorage.removeItem(P);localStorage.removeItem(O);last=null}
function sync(){if(!active)return;let v=localStorage.getItem(P);if(v===last)return;v?localStorage.setItem(key(active.id),v):localStorage.removeItem(key(active.id));last=v}
function load(p){let v=localStorage.getItem(key(p.id));v?localStorage.setItem(P,v):localStorage.removeItem(P);localStorage.setItem(O,p.id);last=v}
function persist(){try{navigator.storage?.persist?.()}catch{}}
function choose(){let r=read(),has=r.profiles.length;panel.innerHTML=`<div class="profile-panel-header"><div><p class="profile-eyebrow">WELCOME</p><h2>${has?"Choose your learner":"Create your first learner"}</h2><p>${has?"Select a local profile and enter its PIN.":"Each learner receives separate progress on this device."}</p></div></div>${has?`<div class="profile-list">${r.profiles.sort((a,b)=>String(b.lastUsedAt||"").localeCompare(String(a.lastUsedAt||""))).map(p=>{let a=av(p.avatarId);return`<button class="profile-choice" data-p="${p.id}"><img src="${a.src}" alt=""><span><strong>${esc(p.name)}</strong><small>${esc(a.title)}</small></span></button>`}).join("")}<button class="profile-choice profile-add-card" data-new><span class="profile-add-icon">＋</span><span>Add another learner</span></button></div>`:`<button class="profile-btn" data-new>Create learner profile</button>`}<div class="profile-info-note"><strong>Stored locally:</strong> clearing website data, private browsing, or changing browsers may remove access. Keep using JSON backups.</div>`}
function login(pid){let p=read().profiles.find(x=>x.id===pid);if(!p)return choose();let a=av(p.avatarId);panel.innerHTML=`<div class="profile-login-title"><img class="profile-login-avatar" src="${a.src}" alt=""><p class="profile-eyebrow">${esc(a.title).toUpperCase()}</p><h2>${esc(p.name)}</h2><p>Enter your local PIN to continue.</p></div><form id="login" class="profile-form"><label class="profile-field"><span>PIN</span><input id="pin" type="password" inputmode="numeric" minlength="4" maxlength="6" pattern="[0-9]{4,6}" required autofocus><small>Four to six numbers.</small></label><div id="err" class="profile-error"></div><div class="profile-actions"><button class="profile-btn secondary" type="button" data-back>Back</button><button class="profile-btn">Open Salita Quest</button></div></form><div class="profile-info-note">This is a casual local profile lock, not a secure online account.</div>`;q("#login").onsubmit=async e=>{e.preventDefault();let pin=q("#pin").value.trim(),b=e.submitter;if(!/^\d{4,6}$/.test(pin))return q("#err").textContent="Enter the four- to six-digit PIN.";b.disabled=true;b.textContent="Checking…";if(await hash(pin,p.pinSalt)!==p.pinHash){q("#err").textContent="That PIN is not correct.";b.disabled=false;b.textContent="Open Salita Quest";q("#pin").select();return}open(p)}}
function create(){let has=read().profiles.length;panel.innerHTML=`<div class="profile-panel-header"><div><p class="profile-eyebrow">NEW LOCAL PROFILE</p><h2>Create a learner</h2><p>Choose a Philippine species avatar and protect the profile with a PIN.</p></div></div><form id="create" class="profile-form"><label class="profile-field"><span>Learner name</span><input id="name" maxlength="24" required></label><div class="profile-pin-row"><label class="profile-field"><span>Create PIN</span><input id="p1" type="password" inputmode="numeric" minlength="4" maxlength="6" required></label><label class="profile-field"><span>Confirm PIN</span><input id="p2" type="password" inputmode="numeric" minlength="4" maxlength="6" required></label></div><div class="profile-avatar-heading"><strong>Choose your avatar</strong><small>Philippine native flora and fauna</small></div><div class="avatar-grid">${V.map((a,i)=>`<div class="avatar-option"><input id="a-${a.id}" type="radio" name="avatar" value="${a.id}" ${i?"":"checked"}><label for="a-${a.id}"><img src="${a.src}" alt=""><strong>${a.title}</strong><small>${a.description}</small></label></div>`).join("")}</div><label class="profile-consent"><input id="consent" type="checkbox" required><span>I understand that this learner’s profile and progress will be stored in this browser on this device.</span></label><div id="err" class="profile-error"></div><div class="profile-actions">${has?'<button class="profile-btn secondary" type="button" data-back>Back</button>':""}<button class="profile-btn">Create and continue</button></div></form>`;q("#create").onsubmit=async e=>{e.preventDefault();let r=read(),name=q("#name").value.trim().replace(/\s+/g," "),p1=q("#p1").value.trim(),p2=q("#p2").value.trim(),error=q("#err");if(!name||name.length>24)return error.textContent="Enter a learner name of up to 24 characters.";if(r.profiles.some(p=>p.name.toLowerCase()===name.toLowerCase()))return error.textContent="That learner name already exists.";if(!/^\d{4,6}$/.test(p1))return error.textContent="Create a PIN containing four to six numbers.";if(p1!==p2)return error.textContent="The PIN entries do not match.";if(!q("#consent").checked)return error.textContent="Accept local storage before continuing.";let s=salt(),p={id:id(),name,avatarId:q('input[name="avatar"]:checked').value,pinSalt:s,pinHash:await hash(p1,s),createdAt:new Date().toISOString(),lastUsedAt:new Date().toISOString(),consentVersion:1},old=r.profiles.length?null:legacy();r.profiles.push(p);write(r);if(old)localStorage.setItem(key(p.id),old);open(p);note(old?"Profile created. Existing progress was preserved.":"Learner profile created.")}}
function decorate(){try{let d=frame.contentDocument,a=av(active.avatarId),el=d.querySelector(".player-avatar");if(el){el.innerHTML=`<img src="${a.src}" alt="${esc(a.title)}">`;el.style.overflow="hidden";let st=d.createElement("style");st.textContent=".player-avatar img{width:100%;height:100%;object-fit:contain;image-rendering:pixelated}";d.head.append(st)}let v=d.querySelector(".version-label");if(v)v.textContent="Version 5.4 Local Profiles"}catch{}}
function open(p){let r=read(),x=r.profiles.find(z=>z.id===p.id);x.lastUsedAt=new Date().toISOString();write(r);active=x;sessionStorage.setItem(A,x.id);load(x);q("#activeProfileName").textContent=x.name;let a=av(x.avatarId);q("#activeProfileAvatar").src=a.src;gate.hidden=true;stage.hidden=false;timer=setInterval(sync,800);persist();frame.src=`app.html?profile=${encodeURIComponent(x.id)}`}
function close(msg="You are logged out."){sync();clearInterval(timer);frame.src="about:blank";sessionStorage.removeItem(A);active=null;clear();stage.hidden=true;gate.hidden=false;choose();note(msg)}
panel.onclick=e=>{let t=e.target.closest("[data-p],[data-new],[data-back]");if(!t)return;t.dataset.p?login(t.dataset.p):t.hasAttribute("data-new")?create():choose()};q("#changeLearnerBtn").onclick=()=>close("Choose another learner.");q("#logoutLearnerBtn").onclick=()=>close();frame.onload=decorate;window.addEventListener("beforeunload",sync);document.addEventListener("visibilitychange",()=>document.hidden&&sync());
(function init(){try{localStorage.setItem("__sq","1");localStorage.removeItem("__sq")}catch{panel.innerHTML='<h2>Local storage is unavailable</h2><p>Leave private browsing or enable site storage, then reload.</p>';return}recover();let r=read(),p=r.profiles.find(x=>x.id===sessionStorage.getItem(A));p?open(p):(sessionStorage.removeItem(A),clear(),choose());if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js").catch(()=>{})})();
})();
